### ISSUE TITLE
Possible to get the "Paths"

### ISSUE THREAD

**Issue by damien-reyre** [ngosang/restic-exporter#17]
Hello,

Thanks for your work. I do appreciate what you did.

I'm just asking if that's possible to get the "Paths" for printing in Grafana?

![image](https://github.com/ngosang/restic-exporter/assets/117079206/8539c46a-47aa-48e5-8429-0121934cd3bb)

 Thanks

**Comment by damien-reyre** [comment]
What I would like, it's to have a new column in the table for the backup where the path is mentioned as:

**Hostname | TAG | Path | Last backup | Last backup (since)**

**Comment by ngosang** [comment]
Included in release 1.3.0. Check the readme, it's disabled by default.

**Comment by damien-reyre** [comment]
Wonderful. Thank so much.
