### ISSUE TITLE
Also allow restic environment variables

### ISSUE THREAD

**Issue by CommanderRedYT** [ngosang/restic-exporter#21]
It would be nice if the script also supports variables from https://restic.readthedocs.io/en/latest/040_backup.html#environment-variables like `RESTIC_REPOSITORY` etc.

Then one could re-use the backup.env file for this script.

**Comment by zauberstuhl** [comment]
@CommanderRedYT  it already does. If you remove the obsolete checks from the script you can use all environment variables from restic. The exporter is a simple wrapper around the restic cli tool.

I did it and it works perfectly:
* https://codeberg.org/lukasmatt/restic-exporter/commit/d54ae6e358c0ee26804ac76d5d88f8582b7b48bb
* https://codeberg.org/lukasmatt/restic-exporter/commit/245d832a19c8e6eae28d4e1c4b9df3ff1bff6a8b


Best

**Comment by ngosang** [comment]
Fixed in 1.5.0 / 4efcaba7c5aa4969b71d7ca6cf77c072d0587329
