### ISSUE TITLE
Support for multiple tags?

### ISSUE THREAD

**Issue by glitchsys** [ngosang/restic-exporter#23]
On line 186 of restic-exporter.py you're only including the first tag in the array.  So if there's multiple tags in a backup, only the first tag is showing up in Grafana.

Can line 186 be changed to:
`"snapshot_tag": ",".join(snap["tags"]) if "tags" in snap else "",`

to support multiple tags like how it supports multiple paths? 

The only issue I can think of is if somebody wrote a dashboard or whatever and only expects there to be a single tag. If you suddenly start showing 2 or 3 tags, it may cause issues. I doubt this is an issue though but on the off chance, you could make it an optional environment variable like `INCLUDE_ALLPATHS=true`   and default it to false.  That's probably overkill though.

**Comment by ngosang** [comment]
Fixed in 1.5.0 / 10dae8da3a7a055d9755fa46969443f0febd097f
