### ISSUE TITLE
multi repository

### ISSUE THREAD

**Issue by shadowchmod** [ngosang/restic-exporter#26]
Hello everyone,
I want to use 'restic-exporter' with multiple repositories. Is the function already operational?
I have the same password for all these repositories, is it possible?

The goal: I am using Prometheus and Grafana on an external server, and I would like to have my repositories monitored there.

My configuration file example with multiple users: RESTIC_REPOSITORY=rest:https://login:password@url/:port/path/users/

P.S.: I can start restic-exporter with a single repository.

Thank you for your help.

**Comment by ngosang** [comment]
Multi repository is not supported and it's not planned. You can setup 2 exporters with different configuration. The exporter is lightweight.
