### ISSUE TITLE
[FEATURE] Multiple repo support

### ISSUE THREAD

**Issue by PovilasID** [ngosang/restic-exporter#6]
Hey,

I have a couple of restic instances backing up to different repos. I am fine with running multiple exporter instances (1 exporter per repo) but it would be nice to get an option a variable in grafan dashboard to merge all data for all/repo1/repo2 to have everything in single view :)

**Comment by ngosang** [comment]
I prefer to keep it simple. The exporter is very light and you can run several instances.
The exported metrics have this format:
```
restic_check_success{instance="192.168.1.191:8889", job="restic-exporter"}
```
The current Grafana dashboard will show the metrics from all exporters in a single dashboard. If you want to filter by repository you could add a combo/selector/filter with the `instance` name.
